// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN4YEi3yiIFcUq188jU-87gDxyQ9v5rUs',
    appId: '1:695374299026:web:a0f26ac9291c6d6a1acb4b',
    messagingSenderId: '695374299026',
    projectId: 'chat-app-a2b3c',
    authDomain: 'chat-app-a2b3c.firebaseapp.com',
    storageBucket: 'chat-app-a2b3c.appspot.com',
    measurementId: 'G-5N5F1FJPQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeDRhfOvsWmaQ6XoeXXfe8kfsZbXXD8qk',
    appId: '1:695374299026:android:1f76bccb1a174cc61acb4b',
    messagingSenderId: '695374299026',
    projectId: 'chat-app-a2b3c',
    storageBucket: 'chat-app-a2b3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm_W3XMmtvQ1_3IPSf1i9GSQLcdPGu2wc',
    appId: '1:695374299026:ios:c2db0d8105036f401acb4b',
    messagingSenderId: '695374299026',
    projectId: 'chat-app-a2b3c',
    storageBucket: 'chat-app-a2b3c.appspot.com',
    iosClientId: '695374299026-i04ur77s79d7hsje67s37io2fsq12vbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm_W3XMmtvQ1_3IPSf1i9GSQLcdPGu2wc',
    appId: '1:695374299026:ios:c2db0d8105036f401acb4b',
    messagingSenderId: '695374299026',
    projectId: 'chat-app-a2b3c',
    storageBucket: 'chat-app-a2b3c.appspot.com',
    iosClientId: '695374299026-i04ur77s79d7hsje67s37io2fsq12vbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppProject',
  );
}
